name: Host System Builder

on:
  push:
  pull_request:


jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-python@v2.2.2
      with:
        python-version: '3.9.x'
    - run: cargo build
    - run: cargo test

  ci_build_distro_ubuntu:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/ubuntu-host:latest"
    steps:
    - uses: actions/checkout@v2.3.4
    - run: cargo build && cargo test
      working-directory: .

  ci_build_distro_debian:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/debian-host:latest"
    steps:
    - uses: actions/checkout@v2.3.4
    - run: cargo build && cargo test
      working-directory: .

  ci_build_distro_fedora:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/fedora-host:latest"
    steps:
    - uses: actions/checkout@v2.3.4
    - run: cargo build && cargo test
      working-directory: .

  ci_build_distro_archlinux:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/archlinux-host:latest"
    steps:
    - uses: actions/checkout@v2.3.4
    - run: cargo build && cargo test
      working-directory: .

  ci_build_distro_opensuse:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/opensuse-host:latest"
    steps:
    - uses: actions/checkout@v2.3.4
    - run: cargo build && cargo test
      working-directory: .
