name: Host System Builder

on:
  push:
  pull_request:


jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - run: cargo build
    - run: cargo test

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - run: cargo build
    - run: cargo test

  chrome_book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v1.0.5
    - run: chromedriver --url-base=/wd/hub &
    - run: cargo build && cargo test

  ci_build_distro_ubuntu:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/ubuntu-host:latest"
    steps:
    - uses: actions/checkout@v2.3.4
    - run: cargo build && cargo test
      working-directory: .

  ci_build_distro_debian:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/debian-host:latest"
    steps:
    - uses: actions/checkout@v2.3.4
    - run: cargo build && cargo test
      working-directory: .

  ci_build_distro_fedora:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/fedora-host:latest"
    steps:
    - uses: actions/checkout@v2.3.4
    - run: cargo build && cargo test
      working-directory: .

  ci_build_distro_archlinux:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/archlinux-host:latest"
    steps:
    - uses: actions/checkout@v2.3.4
    - run: cargo build && cargo test
      working-directory: .

  ci_build_distro_opensuse:
    runs-on: ubuntu-latest
    container:
      image: "michaelbrockus/opensuse-host:latest"
    steps:
    - uses: actions/checkout@v2.3.4
    - run: cargo build && cargo test
      working-directory: .
